"""benchmark evaluation: Set5 / Set14 / BSD100 / Urban100 / Manga109.

Expected layout (HR is required; LR is optional — generated by bicubic if absent):
    benchmarks/
      Set5/HR/*.png            [+ optional]  Set5/LR_bicubic/X4/*.png
      Set14/HR/*.png
      ...

Metric protocol: Y-channel PSNR/SSIM with `scale`-pixel border shave (EDSR/SwinIR/HAT).
Note: published benchmarks use MATLAB bicubic for LR generation; if you only have HR we
downsample with PIL bicubic, which differs marginally — prefer providing the official LR sets
for exact comparability.
"""
import os
import glob
import json
import csv
import argparse
import torch
from PIL import Image
from torchvision import transforms

from config import get_config, available_presets
from models import FrequSpatialGenerator
from utils.metrics import tensor_to_np, calc_psnr, calc_ssim, match_size
from utils.tiling import tiled_forward, self_ensemble_forward
from utils.misc import set_seed, count_params, count_flops, measure_latency

_to_tensor = transforms.ToTensor()
DEFAULT_SETS = ["Set5", "Set14", "BSD100", "Urban100", "Manga109"]


def _load_pair(hr_path, lr_dir, scale):
    img_id = os.path.splitext(os.path.basename(hr_path))[0]
    hr = Image.open(hr_path).convert("RGB")
    # crop HR so its size is divisible by scale (LR is exactly HR/scale)
    w, h = hr.size
    w, h = w - w % scale, h - h % scale
    hr = hr.crop((0, 0, w, h))

    lr_path = None
    if lr_dir and os.path.isdir(lr_dir):
        for cand in (f"{img_id}x{scale}.png", f"{img_id}.png"):
            p = os.path.join(lr_dir, cand)
            if os.path.isfile(p):
                lr_path = p
                break
    if lr_path:
        lr = Image.open(lr_path).convert("RGB")
    else:
        lr = hr.resize((w // scale, h // scale), Image.BICUBIC)
    return _to_tensor(lr), _to_tensor(hr)


@torch.no_grad()
def evaluate_set(model, set_dir, scale, device, tile, self_ensemble):
    hr_paths = sorted(glob.glob(os.path.join(set_dir, "HR", "*")))
    if not hr_paths:
        hr_paths = sorted(glob.glob(os.path.join(set_dir, "*.png")))  # flat layout fallback
    if not hr_paths:
        return None
    lr_dir = os.path.join(set_dir, "LR_bicubic", f"X{scale}")

    def base_forward(x):
        return tiled_forward(model, x, scale=scale, tile=tile, overlap=tile // 6)

    psnrs, ssims = [], []
    for hr_path in hr_paths:
        lr, hr = _load_pair(hr_path, lr_dir, scale)
        lr = lr.unsqueeze(0).to(device)
        if self_ensemble:
            sr = self_ensemble_forward(base_forward, lr)
        else:
            sr = base_forward(lr)
        sr = sr.clamp(0, 1)[0]
        sr, hr = match_size(sr, hr)          # guard: scale*LR need not equal HR exactly
        p, t = tensor_to_np(sr), tensor_to_np(hr)
        psnrs.append(calc_psnr(p, t, crop_border=scale))
        ssims.append(calc_ssim(p, t, crop_border=scale))
    return sum(psnrs) / len(psnrs), sum(ssims) / len(ssims), len(psnrs)


def load_model(ckpt_path, cfg, device, use_ema=True):
    model = FrequSpatialGenerator(cfg.model).to(device).eval()
    ckpt = torch.load(ckpt_path, map_location=device)
    state = {k.replace("module.", ""): v for k, v in ckpt["generator"].items()}
    model.load_state_dict(state)
    if use_ema and ckpt.get("ema", {}).get("shadow"):
        shadow = ckpt["ema"]["shadow"]
        applied = 0
        for name, param in model.named_parameters():
            if name in shadow:
                param.data.copy_(shadow[name].to(param.device).to(param.dtype))
                applied += 1
        print(f"[eval] applied EMA weights ({applied} tensors)")
    return model


def main():
    parser = argparse.ArgumentParser(description="Benchmark evaluation")
    parser.add_argument("--ckpt", type=str, required=True, help="checkpoint path (e.g. results/checkpoints/best.pth)")
    parser.add_argument("--scale", type=int, default=4)
    parser.add_argument("--preset", type=str, default="proposed", choices=available_presets())
    parser.add_argument("--bench_root", type=str, default="benchmarks")
    parser.add_argument("--sets", type=str, nargs="*", default=DEFAULT_SETS)
    # NOTE: must match TrainConfig.val_tile — SR-MoSO is a *global* operator, so the tile size
    # changes its effective receptive field and hence the reported PSNR.
    parser.add_argument("--tile", type=int, default=256, help="LR tile size for tiled inference")
    parser.add_argument("--self_ensemble", action="store_true", help="x8 self-ensemble")
    parser.add_argument("--no_ema", action="store_true", help="use raw (non-EMA) weights")
    parser.add_argument("--out_json", type=str, default=None, help="write results JSON here")
    parser.add_argument("--out_csv", type=str, default=None, help="write results CSV here")
    args = parser.parse_args()

    set_seed(0)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    cfg = get_config(args.preset)
    cfg.model.scale = args.scale
    cfg.validate()

    model = load_model(args.ckpt, cfg, device, use_ema=not args.no_ema)

    # complexity at the conventional 1280x720 OUTPUT size (params / FLOPs / latency)
    params_m = count_params(model)
    bench_shape = (1, 3, 720 // args.scale, 1280 // args.scale)
    gflops = count_flops(model, input_shape=bench_shape, device=device)
    ms = measure_latency(model, bench_shape, device=device)
    print(f"\nmodel: {params_m:.3f}M params | "
          f"{f'{gflops:.2f} GFLOPs' if gflops >= 0 else 'GFLOPs n/a (pip install fvcore)'} | "
          f"{ms:.1f} ms  @1280x720 out")

    print(f"\n{'Dataset':<12} {'PSNR(dB)':>10} {'SSIM':>8} {'#img':>6}")
    print("-" * 40)
    results = {}                                                    # {set: {psnr, ssim, n}}
    for name in args.sets:
        set_dir = os.path.join(args.bench_root, name)
        if not os.path.isdir(set_dir):
            print(f"{name:<12} {'(missing)':>10}")
            continue
        res = evaluate_set(model, set_dir, args.scale, device, args.tile, args.self_ensemble)
        if res is None:
            print(f"{name:<12} {'(no imgs)':>10}")
            continue
        psnr, ssim, n = res
        results[name] = {"psnr": psnr, "ssim": ssim, "n": n}
        print(f"{name:<12} {psnr:>10.3f} {ssim:>8.4f} {n:>6d}")

    # persist results (params + per-set PSNR/SSIM) for downstream aggregation
    meta = {"preset": args.preset, "scale": args.scale, "params_M": params_m,
            "gflops": gflops, "latency_ms": ms,
            "self_ensemble": args.self_ensemble, "ema": not args.no_ema, "sets": results}
    if args.out_json:
        os.makedirs(os.path.dirname(args.out_json) or ".", exist_ok=True)
        with open(args.out_json, "w") as f:
            json.dump(meta, f, indent=2)
        print(f"[eval] wrote {args.out_json}")
    if args.out_csv:
        os.makedirs(os.path.dirname(args.out_csv) or ".", exist_ok=True)
        with open(args.out_csv, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["preset", "scale", "params_M", "gflops", "latency_ms", "dataset", "psnr", "ssim", "n"])
            for s, r in results.items():
                w.writerow([args.preset, args.scale, f"{params_m:.4f}", f"{gflops:.2f}", f"{ms:.2f}", s,
                            f"{r['psnr']:.4f}", f"{r['ssim']:.4f}", r["n"]])
        print(f"[eval] wrote {args.out_csv}")


if __name__ == "__main__":
    main()
